name: release
on:
  push:
    tags:
      # Run on every proper semver tag
      - 'v[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      # Release the version
      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Received workflow_dispatch event with version ${{ github.ref_name }}"
          echo "Releasing version ${{  github.ref_name }}"
          gh release create -R merschformann/flow-experiment-api ${{  github.ref_name }} -t ${{  github.ref_name }} -n ${{  github.ref_name }}
